### ISSUE TITLE
Fala Guzz, Douglas aqui!

### ISSUE THREAD

**Issue by douglashudsonti** [AugustoTI/invoice-app#1]
Mano não te achei mais no discord, me passa seu whatsapp? Precisava falar com vc!

**Comment by AugustoTI** [comment]
Carai kkkk Quanto tempo pô! Man, eu passo sim. Só não aqui
No lugar por agora, me add no Discord: guzz_

**Comment by AugustoTI** [comment]
> Mano não te achei mais no discord, me passa seu whatsapp? Precisava falar com vc!

Carai kkkk Quanto tempo pô! Man, eu passo sim. Só não aqui
No lugar por agora, me add no Discord: guzz_
